"""moved municipality from customer to account

Revision ID: 2fcc54e35555
Revises: 63abb2723638
Create Date: 2025-05-22 22:06:04.365867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcc54e35555'
down_revision: Union[str, None] = '63abb2723638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('municipality', sa.String(), nullable=False))
    op.drop_column('customers', 'municipality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('municipality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'municipality')
    # ### end Alembic commands ###
