"""in customer model changed street to address

Revision ID: 63abb2723638
Revises: 06eb55d9458e
Create Date: 2025-05-22 22:02:31.135677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63abb2723638'
down_revision: Union[str, None] = '06eb55d9458e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('customers', 'street')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
