"""fixed unique ssn

Revision ID: 7d4b92ad947c
Revises: 1146686a50a4
Create Date: 2025-05-21 20:37:49.019479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4b92ad947c'
down_revision: Union[str, None] = '1146686a50a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_ssn_key', 'accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('accounts_ssn_key', 'accounts', ['ssn'])
    # ### end Alembic commands ###
